/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "accountWebAdmin": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "accountWebUser": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "auth": {
      "type": "sst.aws.Auth"
      "url": string
    }
    "bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "gameWebAdmin": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "gameWebUser": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "router": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}