/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GameTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GameWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "auth0_APP_BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "auth0_AUTH0_CLIENT_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "auth0_AUTH0_CLIENT_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "auth0_AUTH0_DOMAIN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "auth0_AUTH0_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "openai_OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}